### ISSUE TITLE
invalid syntaxc at line 9 HW:str

### ISSUE THREAD

**Issue by Musrar** [anezih/mobi2stardict#1]
Hello, when I try to use the script I get this error:

python mobi2stardict.py --html book.html --dict-name GDLC --textual --chunked --fix-links --author "Enciclopèdia Catalana"
  File "mobi2stardict.py", line 9
    HW: str
      ^
SyntaxError: invalid syntax

I have both lxml and beautiful soup installed (I use bs4 to parse some online dictionaries), so I don't know what this error might be coming from. Also I might add I'm a bit of an amateur when it comes to programming.

Thanks

**Comment by anezih** [comment]
Which python version do you use? Try with the latest version, if possible.
