### ISSUE TITLE
Getting error converting to gls

### ISSUE THREAD

**Issue by colibris79** [anezih/mobi2stardict#3]
Hi
I am using python 3.10 in Ubuntu 22.04 with all the dependencies mentioned installed.
I get the following error while trying to convert from a book.html  file (got from a .mobi dictionary through KindleUnpack) to gls. Placed both files in the same directory :
```

$ python mobi2stardict.py --html book.html --fix-links --dict-name MALAZ --gls --textual --chunked
Traceback (most recent call last):
  File "/home/m/Downloads/mobi2stardict.py", line 231, in <module>
    convert(args.html_file, args.dict_name, args.author, args.fix_links,
  File "/home/m/Downloads/mobi2stardict.py", line 91, in convert
    book = f.read()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 292: invalid start byte
```
Any way I could solve this error? been trying for a while without any luck : (

Thanks

**Comment by anezih** [comment]
I've updated some parts. Could you re-read the README and try again?

**Comment by colibris79** [comment]
Great, thanks! :)
